### ISSUE TITLE
PROG 7 

### ISSUE THREAD

**Issue by SashankRaja** [Chandan-CV/Amaatra-Grade-12-Lab-Programs#1]
def fun(A):
     l=len(A)
     for i in range(0,l,2):
         tmp=A[i]
         A[i]=A[i+1]
         A[i+1]=tmp
     print(A)

A=eval(input("Enter a list: "))
if(len(A)%2==0):
    fun(A)

**Comment by Chandan-CV** [comment]
This is the last program we did today right? That's cool I will update it!

you can fork this repository, make changes there and send a pull request if you want it to be merged directly.

**Comment by SashankRaja** [comment]
Yup.I don’t know how to use GitHub very well lol from next time I will send a pull req   Sent from Mail for Windows 10 From: Chandan CVSent: 29 June 2021 18:21To: Chandan-CV/Amaatra-Grade-12-Lab-ProgramsCc: Sashank; AuthorSubject: Re: [Chandan-CV/Amaatra-Grade-12-Lab-Programs] PROG 7 (#1) This is the last program we did today right? That's cool I will update it!you can fork this repository, make changes there and send a pull request if you want it to be merged directly.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
