### ISSUE TITLE
Practical Program 3

### ISSUE THREAD

**Issue by adithyayog** [Chandan-CV/Amaatra-Grade-12-Lab-Programs#14]
What your program does is pick the lines the DON'T have 'a' and append them to a new file, without changing the original one. 

I think the question asks you to REMOVE lines WITH 'a' in the original file, AND append those same lines in the new file.

This is the code I got after editing yours:

```
f = open("practical programs/pg3/file.txt", w+)

f2 = open("practical programs/pg3/targetfile.txt","w")
a = f.readlines()
a1=a
af=[]
for x in range(0,len(a)):
    if ("a" in a[x]):         
        af.append(a[x])
        a1[x]=""             # replaces 'a' with empty string
f.seek(0)
f2.writelines(af)
f.writelines(a1)           # writes edited text on original string
```

**Comment by Chandan-CV** [comment]
Ohhh I see, so basically, we remove the lines with "a" in the original file and transfer those to the target file right?

**Comment by Chandan-CV** [comment]
Done, ig it works correctly now. Can you check and confirm?

Thank you!!!

**Comment by adithyayog** [comment]
yup, looks good, no problem.

**Comment by Chandan-CV** [comment]
oh peace, I will close this issue then.

Thank you for contributing!!!!
